server:
  port: 8881
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
    #  uri: http://localhost:8888/
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8889/eureka/

